# syntax=docker/dockerfile:1
# pull official base image
FROM python:3.9-slim
# set work directory
WORKDIR /usr/src/app
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/usr/src/app
# install base dependencies
RUN pip install --upgrade pip
COPY requirements/*.txt ./
COPY src/tests/functional/requirements.txt ./
RUN pip3 install -r base.txt -r requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends netcat
# create directory for the app user
RUN mkdir -p /home/src
# create the app user
RUN addgroup --system app && adduser --system --group app
# create the appropriate directories
ENV HOME=/home/src
WORKDIR $HOME
ENV PYTHONPATH=$HOME
# copy entrypoint.prod.sh
COPY ./entrypoint.test.sh .
RUN sed -i 's/\r$//g'  $HOME/entrypoint.test.sh
RUN chmod +x  $HOME/entrypoint.test.sh
# copy app and tests dirs
COPY ./src $HOME
# chown all the files to the app user
RUN chown -R app:app $HOME
# change to the app user
USER app
EXPOSE 8000 8088
# run entrypoint.prod.sh
ENTRYPOINT ["/home/src/entrypoint.test.sh"]
