version: "3.8"
   
services:

  tests-auth:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: testing-auth
    ports:
      - "8088:8088"
    depends_on:
      - db-auth
      - redis
    volumes:
      - ./src:/usr/src
    env_file:
      - .env
    networks:
      - tests
    environment:
      - LOG_LEVEL=INFO
      - TEST_TESTING=True

  redis:
    image: redis:6.2.5
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    command:
      - redis-server
    networks:
      - tests

  db-auth:
    image: postgres:13.0
    container_name: db-auth
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - tests

networks:
  tests: