# syntax=docker/dockerfile:1
# pull official base image
FROM python:3.9-slim
# set work directory
WORKDIR /usr/src/app
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# install base dependencies
RUN pip install --upgrade pip
COPY requirements/api.txt ./
RUN pip3 install -r api.txt
# copy app files
COPY ./src/app /usr/src/app/
COPY ./src/migrations /usr/src/migrations
# set workdir
WORKDIR /usr/src
ENV PYTHONPATH=/usr/src
# start api
CMD python app/main.py